FROM node:18-alpine as development

WORKDIR /usr/src/app

COPY package.json ./

COPY package-lock.json ./

# TODO: Remove the "force" tag when upgrade @nestjs/typeorm to v9
RUN npm install --force

COPY . ./